config/routes.rb
Rails.application.routes.draw do
  resources :members

  root :to =>'home#index'
  devise_for :users
    get 'users/sign_in'
    post 'users/sign_in'
    get 'users/sign_out'
  

end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user!
	
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @members = Member.all
    respond_with(@members)
  end

  def show
    respond_with(@member)
  end

  def new
    @member = Member.new
    respond_with(@member)
  end

  def edit
  end

  def create
    @member = Member.new(member_params)
    flash[:notice] = 'Member was successfully created.' if @member.save
    respond_with(@member)
  end

  def update
    flash[:notice] = 'Member was successfully updated.' if @member.update(member_params)
    respond_with(@member)
  end

  def destroy
    @member.destroy
    respond_with(@member)
  end

  private
    def set_member
      @member = Member.find(params[:id])
    end

    def member_params
      params.require(:member).permit(:name, :uname, :dob, :gender, :contact, :email, :mpass, :cmpass)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/home/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/home/index.html.haml
#block-text.block
  .content
    %h2.title Home
    .inner
      %p.first
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        = succeed "," do
          %span.hightlight Excepteur sint occaecat cupidatat non proident
        sunt in culpa qui officia deserunt mollit anim id est laborum.
      %p
        %span.small Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
      %p
        %span.gray Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
      %hr/
      %p
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        = succeed "," do
          %span.hightlight Excepteur sint occaecat cupidatat non proident
        sunt in culpa qui officia deserunt mollit anim id est laborum.
- content_for :sidebar, render(:partial => 'sidebar')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Iface
    = stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override", :cache => true
    = javascript_include_tag :defaults, :cache => true
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} Iface
        #user-navigation
          %ul.wat-cf
            %li
              %a{:href => "#"}= t("web-app-theme.profile", :default => "Profile")
            %li
              %a{:href => "#"}= t("web-app-theme.settings", :default => "Settings")
            %li
              = link_to t("web-app-theme.logout", :default => "Logout"), destroy_user_session_path
        #main-navigation
          %ul.wat-cf
            %li{ :class => (params[:controller] == "home" ? "first active" : "first") }
              = link_to "Home"
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} Iface.
        #sidebar
          = yield :sidebar

app/views/layouts/sign.html.haml
!!!
%html
  %head
    %title Iface
    = stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override", :cache => true
    = csrf_meta_tag
  %body
    #container
      #box
        = yield

app/views/members/_form.html.haml
= form_for @member do |f|
  - if @member.errors.any?
    #error_explanation
      %h2= "#{pluralize(@member.errors.count, "error")} prohibited this member from being saved:"
      %ul
        - @member.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :uname
    = f.text_field :uname
  .field
    = f.label :dob
    = f.datetime_select :dob
  .field
    = f.label :gender
    = f.text_field :gender
  .field
    = f.label :contact
    = f.number_field :contact
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :mpass
    = f.text_field :mpass
  .field
    = f.label :cmpass
    = f.text_field :cmpass
  .actions
    = f.submit 'Save'

app/views/members/_sidebar.html.haml
!!!
.block.notice
  %h3 Group Friend
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Online
  %ul.navigation
    %li
      %a{:href => "#"} Friend 1
    %li
      %a{:href => "#"} Friend 2

app/views/members/edit.html.haml
!!!
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", members_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_member_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_member_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Member
    .inner
      = form_for @member, :url => member_path(@member), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/members/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", members_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_member_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      New Member
      .inner
        %table
          %thead
            %tr
              %th Name
              %th Uname
              %th Dob
              %th Gender
              %th Contact
              %th Email
              %th Mpass
              %th Cmpass
              %th
              %th
              %th
              
          %tbody
            - @members.each do |member|
              %tr
                %td= member.name
                %td= member.uname
                %td= member.dob
                %td= member.gender
                %td= member.contact
                %td= member.email
                %td= member.mpass
                %td= member.cmpass
                %td.last
                  = link_to "#{t("web-app-theme.show", :default => "Show")}", member_path(member)
                  |
                  \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_member_path(member)} |
                  \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", member_path(member), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
- content_for :sidebar, render(:partial => 'sidebar')

app/views/members/new.html.haml
%h1 New member

= render 'form'

= link_to 'Back', members_path

app/views/members/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @member.name
%p
  %b Uname:
  = @member.uname
%p
  %b Dob:
  = @member.dob
%p
  %b Gender:
  = @member.gender
%p
  %b Contact:
  = @member.contact
%p
  %b Email:
  = @member.email
%p
  %b Mpass:
  = @member.mpass
%p
  %b Cmpass:
  = @member.cmpass

= link_to 'Edit', edit_member_path(@member)
\|
= link_to 'Back', members_path